"""update expense table by adding column of amount and date

Revision ID: 00bad0402c05
Revises: 50cfec5d5cb6
Create Date: 2026-09-16 17:27:58.196888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bad0402c05'
down_revision: Union[str, Sequence[str], None] = '50cfec5d5cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'expenses',
        sa.Column('amount', sa.Float(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'expenses',
        sa.Column('date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')),
    )
    op.alter_column('expenses', 'amount', server_default=None)
    op.alter_column('expenses', 'date', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###
